"""rename destinations to destination

Revision ID: 958a4c1b71b1
Revises: 3e7e241a4cd9
Create Date: 2025-06-01 21:58:02.680023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958a4c1b71b1'
down_revision: Union[str, None] = '3e7e241a4cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('destination', sa.String(), nullable=True))
    op.drop_column('trips', 'destinations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('destinations', sa.VARCHAR(), nullable=True))
    op.drop_column('trips', 'destination')
    # ### end Alembic commands ###
